### PR TITLE
CORE-8968: update postgres version 

### PR DESCRIPTION
**Pull request by ronanbrowne**
Patch` postgresql` to later minor version and externalize dependency

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by mcgovc** [comment]
Suggestion to run `dos2unix` on the `gradle.properties` file @ronanbrowne

**Review by yarivus — APPROVED** [review]
LGTM

**Review by mcgovc — APPROVED** [review]

**Review by mattbradburyr3 — APPROVED** [review]
Approved

**Pull request merged**
