### PR TITLE
CORE-13261: (to release branch) update dependencies for Hawk1.0.1

### PR DESCRIPTION
**Pull request by anton-subbotin**
- use correct versions for cordaApi, notary server cpb, and combined worker
- remove internal dev dependencies, use csde plugin from maven central
- remove commented out test code

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Comment by anton-subbotin** [comment]
Tests passed: https://ci02.dev.r3.com/job/QA/job/Craft_Tests/job/qa-regpack-csde/job/main/181/

**Review by abellagonzalo — APPROVED** [review]
LGTM

**Comment by abellagonzalo** [comment]
@ronanbrowne do you know what is the `continuous-integration/jenkins/pr-merge` task?

**Review by yarivus — COMMENTED** [review]
thx @anton-subbotin

**Pull request merged**
