### PR TITLE
CORE-12019 Add some comments and Remove unused dependency

### PR DESCRIPTION
**Pull request by egabrovski-r3**
moved from https://github.com/corda/CSDE-cordapp-template-kotlin/pull/56

### CODE REVIEW

**Review by yarivus — APPROVED** [review]
LGTM

**Review by yarivus — APPROVED** [review]
LGTM
@egabrovski-r3 please refrain from `git rebase`

**Comment by egabrovski-r3** [comment]
qa-regpack-csde test suite is Green

**Review by yarivus — APPROVED** [review]
LGTM

**Review by mattbradburyr3 — APPROVED** [review]

**Pull request merged**
